services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-rm566052
    environment:
      ORACLE_PASSWORD: oracle
      APP_USER: terrasense
      APP_USER_PASSWORD: terrasense
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
    networks:
      - terrasense-net


  app:
    image: docker.io/vitordalmagro/terrasense-api:jlink-v1
    container_name: api-rm566052
    depends_on:
      - oracle
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle:1521/XEPDB1
      SPRING_DATASOURCE_USERNAME: terrasense
      SPRING_DATASOURCE_PASSWORD: terrasense
    networks:
      - terrasense-net

volumes:
  oracle_data:

networks:
  terrasense-net:
    driver: bridge